### ISSUE TITLE
D2 diagram breaks headers below

### ISSUE THREAD

**Issue by mrpatrickpilch** [danieleades/mdbook-d2#19]
Scenario:

Default config in place as indicated in the README.

Input:

````
# Chapter 1

## Test
```d2
a -> b
```

## Again
````

Actual Result:

![image](https://user-images.githubusercontent.com/88005594/217636528-67db246c-262f-42f4-9e5b-386489662eea.png)

My expected result would be more inline with displaying a standard code block, e.g.

````
# Chapter 1

## Test
```
a -> b
```

## Again
````

![image](https://user-images.githubusercontent.com/88005594/217636766-e1ab9054-bc34-4c2d-8360-5971989e9d42.png)

**Comment by danieleades** [comment]
Thanks for the report! Will take a look

**Comment by danieleades** [comment]
@mrpatrickpilch do you want to try installing mdbook-d2 from `main` and see if that solves your problem?

something like

```sh
cargo install --git https://github.com/danieleades/mdbook-d2.git
```

**Comment by mrpatrickpilch** [comment]
@danieleades Looks good now! Thank you!
