### ISSUE TITLE
Consider cutting a GH tag release

### ISSUE THREAD

**Issue by blaggacao** [danieleades/mdbook-d2#34]
The change log states version `0.3.0`, but that is not discoverable from the vcs source, and hence any packaging attempts (from source) may not be version aware.

For that reason, https://github.com/NixOS/nixpkgs/pull/227324 marks the version as `unstable-2023-03-30`. Once you get around to cut a (newer) release here, it will automatically heal, tough.

**Comment by blaggacao** [comment]
If you happen to be looking for tooling support, I can plainly recommend https://github.com/cocogitto/cocogitto

**Comment by danieleades** [comment]
I'm not familiar with the nix use case, but I'll take a look. Likely a few days before I get a chance to look at this

**Comment by classabbyamp** [comment]
+1, please tag this so void can package it (I'm interested in using it in some of our documentation)

**Comment by kevinmichaelchen** [comment]
I'd love to package this in [Tea](https://tea.xyz/)'s pantry, but it relies on a release or tag.

Even a `v0.0.1` would be okay.

**Comment by danieleades** [comment]
apologies for the long convalescence.
I'd be happy to look at a PR for some tooling to improve the release process.

related #46
