### ISSUE TITLE
Ability to load files in addition to inline code blocks

### ISSUE THREAD

**Issue by blaggacao** [danieleades/mdbook-d2#35]
There are good examples from the `mdbook-kroki` preprocessor. It would be convenient to copycat that functionality.

In medias res references:
- [Idea of `<tag>` syntax](https://github.com/JoelCourtney/mdbook-kroki-preprocessor/blob/main/example/src/inline_diagrams.md), which enables
- [a more idiomatic way to reference files](https://github.com/JoelCourtney/mdbook-kroki-preprocessor/blob/main/example/src/referenced_diagrams.md)
- [based on different source roots](https://github.com/JoelCourtney/mdbook-kroki-preprocessor/blob/main/example/src/subchapters/reference_diagram_roots.md)

**Comment by danieleades** [comment]
I like that approach. It does beg the question of why you shouldn't just use the kroki preprocessor (which supports D2), no?

**Comment by blaggacao** [comment]
> just use the kroki preprocessor (which supports D2), no?

The public (free) service has a limitation on base64 data length that quickly becomes a blocker on architecture diagrams.

Additionally, should there be sensitive information in the diagrams it may be against applicable policy to send them to a remote service.

**Comment by danieleades** [comment]
> > just use the kroki preprocessor (which supports D2), no?
> 
> The public (free) service has a limitation on payload length that quickly becomes a blocker on architecture diagrams.
> 
> Additionally, should there be sensitive information in the diagrams it may be against applicable policy to send them to a remote service.

You can run a local kroki instance without too much difficulty, but I take your point.

I'll take a deeper look at kroki's approach. I wouldn't want to implement anything that's going to break syntax highlighting plugins.

PRs welcome!

**Comment by christianjann** [comment]
I used the import feature of d2: https://d2lang.com/tour/imports/, e.g. to load a complete diagram:

````md
```d2
...@my_folder/mydiagram
```
````
Also importing parts of a diagram works.

**Comment by danieleades** [comment]
i take it then that this is already supported by D2 with no need to implement in this plugin?

closing.
