### ISSUE TITLE
Publish Github releases with static Linux binaries

### ISSUE THREAD

**Issue by langston-barrett** [danieleades/mdbook-d2#46]
Hi, thanks for the awesome tool!

I'd like to use this in a CI build. The build would go faster and use fewer resources if I were able to download a statically-linked Linux executable from the Github releases, rather than use `cargo install`. It's actually pretty easy to set up Github Actions to automatically create draft releases with attached static binaries whenever you push a git tag. An example CI setup from one of my own projects is available here: https://github.com/langston-barrett/mdlynx/blob/main/.github/workflows/release.yml

Feel free to close this issue if this doesn't appeal to you or sounds like too much work, I just figured I'd share my use-case and the above link in case it's helpful!

**Comment by danieleades** [comment]
i'm happy to accept a PR for this
