### ISSUE TITLE
Dynamic d2 doesn't stay dynamic

### ISSUE THREAD

**Issue by Vaelatern** [danieleades/mdbook-d2#8]
One killer feature here is the ability to use a d2 link (released in d2 v0.1.4) to link a shape to a different section of the book.

At present though, unlike the original `mdbook-svgbob`, d2 links the svg as an image, instead of taking it "inline". This breaks the ability to click a link on the svg.

Would a pull request be welcome? I've never written rust before, but I could try and cobble together something based on `mdbook-svgbob`

**Comment by danieleades** [comment]
Absolutely a link would be welcome!


If you need any rust tips, give me a shout.

Would the inline version support multiple renderers, or only html?

**Comment by Vaelatern** [comment]
Inline version would only support HTML+SVG

I'm not talking about putting a link around the entire thing, I'm talking about inlining the SVG version completely.

**Comment by danieleades** [comment]
> Inline version would only support HTML+SVG
> 
> I'm not talking about putting a link around the entire thing, I'm talking about inlining the SVG version completely.

understood. You would need to implement a second [`Preprocessor`](https://docs.rs/mdbook/latest/mdbook/preprocess/trait.Preprocessor.html), and handle the renderer support with the `Preprocessor::supports_renderer` method.

You would need to choose the Preprocessor based on the provided configuration
